config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :adress, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_card.html.erb
<div class="card col m-2" style="width: 18rem;">
  <img src="https://picsum.photos/seed/flat,NY/200/200" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%=flat.name%></h5>
    <p class="card-text"><%=flat.description%></p>
    <%=link_to 'Details', flat_path(flat), class: "btn btn-primary" %>
  </div>
</div>

app/views/flats/_form.html.erb
<%=simple_form_for(flat) do |f|%>
  <%=f.input :name%>
  <%=f.input :description%>
  <%=f.input :address%>
  <%=f.input :price_per_night%>
  <%=f.input :number_of_guests%>
  <%=f.submit%>
<%end%>

app/views/flats/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <b>Not AirBNB</b>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Search</a>
        </li>
        <li class="nav-item">
          <%=link_to "Add a flat", new_flat_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Search</a>
            <a class="dropdown-item" href="#">Add flat</a>
            <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
          </div>
        </li>
        <!--li class="nav-item"-->
        <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <%=render "navbar"%>
  <!--TODO-->
  <div class="container">
    <h1>All of our flat (<%=@flats.count%>)</h1>
    <div class="row row-cols-3">
      <%@flats.each do |flat|%>
        <%= render "card", flat: flat%>
      <%end%>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <%=render "navbar"%>
  <!--TODO-->
  <div class="container">
    <h1>Add a flat</h1>
    <%=render 'form', flat: @flat%>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <%=render "navbar"%>
  <!--TODO-->
  <div class="container">
    <h1>Flat detail</h1>
    <%= render "card", flat: @flat%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" c ontent="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>